events {
    
}
http {
    include /etc/nginx/mime.types;
    server {
        listen 80 default_server;
        root /app/public;

        index index.php index.html index.htm;

        # uncomment line below to redirect all requests to index.php
        try_files $uri $uri/ /index.php?$args;

        location ~ \.php$ {
            # 127.0.0.11 es el DNS interno de Docker
            resolver 127.0.0.11 valid=30s;
            set $upstream_php php;

            fastcgi_pass $upstream_php:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;     
        }   
        
    } 
}